import type { CsvSchema } from "./csv";

export const SELLERS_PM_SCHEMA: CsvSchema = {
  name: "SellersPreviousMonth",
  columns: [
    { csv: "CUS_CUST_ID_SEL", db: "cust_id", type: "integer" },
    { csv: "SELLER_URL", db: "seller_url", type: "string" },
    { csv: "VS_PM_STATUS", db: "vs_pm_status", type: "string" },
    { csv: "NMV_USD", db: "nmv_usd", type: "number" },
    { csv: "NMV_LC", db: "nmv_lc", type: "number" },
    { csv: "NMV_LC_1", db: "nmv_lc_1", type: "number" },
    { csv: "NMV_LC_2", db: "nmv_lc_2", type: "number" },
    { csv: "SB", db: "sb", type: "number" },
    { csv: "VS_PM_PCT", db: "vs_pm_pct", type: "number" },
    { csv: "PENETRACAO_3PGM_PCT", db: "penetracao_3pgm_pct", type: "number" },
    { csv: "VS_PM_3PGM_PCT", db: "vs_pm_3pgm_pct", type: "number" },
    { csv: "DATA_ULTIMA_CONCESSAO", db: "data_ultima_concessao", type: "date" },
    { csv: "DATA_EXPIRACAO_CONCESSAO", db: "data_expiracao_concessao", type: "date" },
    { csv: "DIAS_EXPIRACAO", db: "dias_expiracao", type: "integer" },
    { csv: "SNAPSHOT_DATE", db: "snapshot_date", type: "date" },
  ],
};

export const CPP_MENSAL_SCHEMA: CsvSchema = {
  name: "CppMensal",
  columns: [
    { csv: "CUS_CUST_ID_SEL", db: "cus_cust_id_sel", type: "integer" },
    { csv: "TIM_MONTH_ID", db: "tim_month_id", type: "integer" },
    { csv: "CUS_NICKNAME", db: "cus_nickname", type: "string" },
    { csv: "CLUSTER_SELLER", db: "cluster_seller", type: "string" },
    { csv: "SUB_CLUSTER_SELLER", db: "sub_cluster_seller", type: "string" },
    { csv: "CUS_STATE", db: "cus_state", type: "string" },
    { csv: "H_L", db: "h_l", type: "string" },
    { csv: "NIVEL_SOLUCION", db: "nivel_solucion", type: "string" },
    { csv: "FECHA_IN", db: "fecha_in", type: "date" },
    { csv: "FECHA_OUT", db: "fecha_out", type: "date" },
    { csv: "PROGRAMA", db: "programa", type: "string" },
    { csv: "INICIATIVA", db: "iniciativa", type: "string" },
    { csv: "NOMBRE_SOLUCION", db: "nombre_solucion", type: "string" },
    { csv: "MESES_NO_PROGRAMA", db: "meses_no_programa", type: "integer" },
    { csv: "COMPARATIVO", db: "comparativo", type: "string" },
    { csv: "TGMV_LC", db: "tgmv_lc", type: "number" },
    { csv: "TSI", db: "tsi", type: "number" },
    { csv: "F_TGMV_LC", db: "f_tgmv_lc", type: "number" },
    { csv: "F_TSI", db: "f_tsi", type: "number" },
    { csv: "TGMV_LC_FBM", db: "tgmv_lc_fbm", type: "number" },
    { csv: "TGMV_LC_ME2", db: "tgmv_lc_me2", type: "number" },
    { csv: "INV_PADS", db: "inv_pads", type: "number" },
    { csv: "TGMV_LC_PADS", db: "tgmv_lc_pads", type: "number" },
    { csv: "CDP_TGMV_LC", db: "cdp_tgmv_lc", type: "number" },
    { csv: "CDP_TSI", db: "cdp_tsi", type: "number" },
    { csv: "SCORE_FINAL_FULL", db: "score_final_full", type: "number" },
    { csv: "SCORE_FINAL_CDP", db: "score_final_cdp", type: "number" },
    { csv: "SCORE_FINAL_PADS", db: "score_final_pads", type: "number" },
    { csv: "SCORE_FINAL_SERVICOS", db: "score_final_servicos", type: "number" },
    { csv: "SCORE_FINAL_BBF", db: "score_final_bbf", type: "number" },
    { csv: "PONTUACAO_IPI", db: "pontuacao_ipi", type: "number" },
    { csv: "PONTUACAO_HI", db: "pontuacao_hi", type: "number" },
    { csv: "PONTUACAO_SOW", db: "pontuacao_sow", type: "number" },
    { csv: "REP_CURRENT_LEVEL", db: "rep_current_level", type: "string" },
    { csv: "REP_CLAIMS_RATE", db: "rep_claims_rate", type: "number" },
    { csv: "VISITAS", db: "visitas", type: "number" },
    { csv: "TOTAL_LIVELISTINGS", db: "total_livelistings", type: "number" },
  ],
};

export const CDP_MENSAL_SCHEMA: CsvSchema = {
  name: "CdpMensal",
  columns: [
    { csv: "CUS_CUST_ID_SEL", db: "cus_cust_id_sel", type: "integer" },
    { csv: "TIM_MONTH_ID", db: "tim_month_id", type: "integer" },
    { csv: "PROGRAMA", db: "programa", type: "string" },
    { csv: "NOMBRE_SOLUCION", db: "nombre_solucion", type: "string" },
    { csv: "SAFRA", db: "safra", type: "date" },
    { csv: "MESES_NO_PROGRAMA", db: "meses_no_programa", type: "integer" },
    { csv: "F_TGMV_LC", db: "f_tgmv_lc", type: "number" },
    { csv: "F_TGMV_LC_PRE_ACORDO", db: "f_tgmv_lc_pre_acordo", type: "number" },
    { csv: "F_TGMV_LC_AUTOMATIC", db: "f_tgmv_lc_automatic", type: "number" },
    { csv: "F_TGMV_LC_CUSTOM_SELLER", db: "f_tgmv_lc_custom_seller", type: "number" },
    { csv: "F_TGMV_LC_TIERS", db: "f_tgmv_lc_tiers", type: "number" },
    { csv: "F_TGMV_LC_REGULAR", db: "f_tgmv_lc_regular", type: "number" },
    { csv: "F_TGMV_LC_CUPOM", db: "f_tgmv_lc_cupom", type: "number" },
    { csv: "F_TGMV_LC_DXB", db: "f_tgmv_lc_dxb", type: "number" },
    { csv: "F_TGMV_LC_DOD", db: "f_tgmv_lc_dod", type: "number" },
    { csv: "F_TGMV_LC_LIGHTNING", db: "f_tgmv_lc_lightning", type: "number" },
    { csv: "F_TGMV_LC_CDP", db: "f_tgmv_lc_cdp", type: "number" },
    { csv: "CP_INVESTMENTS_LC", db: "cp_investments_lc", type: "number" },
    { csv: "CP_INVESTIMENTS_SELLER_LC", db: "cp_investiments_seller_lc", type: "number" },
    { csv: "TOTAL_REBATES_LC", db: "total_rebates_lc", type: "number" },
    { csv: "TOTAL_INVESTIMENTS_LC", db: "total_investiments_lc", type: "number" },
    { csv: "DT_ATUALIZACAO", db: "dt_atualizacao", type: "date" },
  ],
};

export const LIVELISTINGS_SCHEMA: CsvSchema = {
  name: "LiveListings",
  columns: [
    { csv: "DATA", db: "data", type: "date" },
    { csv: "CUS_CUST_ID_SEL", db: "cus_cust_id_sel", type: "integer" },
    { csv: "CUS_NICKNAME", db: "cus_nickname", type: "string" },
    { csv: "TIM_MONTH_ID", db: "tim_month_id", type: "integer" },
    { csv: "PROGRAMA", db: "programa", type: "string" },
    { csv: "INICIATIVA", db: "iniciativa", type: "string" },
    { csv: "NIVEL_SOLUCION", db: "nivel_solucion", type: "string" },
    { csv: "CLUSTER_SELLER", db: "cluster_seller", type: "string" },
    { csv: "SUB_CLUSTER_SELLER", db: "sub_cluster_seller", type: "string" },
    { csv: "CUS_STATE", db: "cus_state", type: "string" },
    { csv: "H_L", db: "h_l", type: "string" },
    { csv: "VERTICAL", db: "vertical", type: "string" },
    { csv: "DOM_DOMAIN_AGG1", db: "dom_domain_agg1", type: "string" },
    { csv: "DOM_DOMAIN_AGG2", db: "dom_domain_agg2", type: "string" },
    { csv: "DOM_DOMAIN_AGG3", db: "dom_domain_agg3", type: "string" },
    { csv: "CATEGORIA", db: "categoria", type: "string" },
    { csv: "ITENS", db: "itens", type: "integer" },
  ],
};

export const ELEGIBILIDADE_SCHEMA: CsvSchema = {
  name: "Elegibilidade",
  columns: [
    { csv: "CUS_CUST_ID_SEL", db: "cus_cust_id_sel", type: "integer" },
    { csv: "CUS_NICKNAME", db: "cus_nickname", type: "string" },
    { csv: "FLAG_SELLER_OPTIN", db: "flag_seller_optin", type: "boolean" },
    { csv: "FLAG_ITEM_OPTIN", db: "flag_item_optin", type: "boolean" },
    { csv: "PROGRAMA", db: "programa", type: "string" },
    { csv: "NOMBRE_SOLUCION", db: "nombre_solucion", type: "string" },
    { csv: "SAFRA", db: "safra", type: "date" },
    { csv: "MESES_NO_PROGRAMA", db: "meses_no_programa", type: "integer" },
    { csv: "ACAO_RECOMENDADA", db: "acao_recomendada", type: "string" },
    { csv: "FLAG_BEST_PROMO", db: "flag_best_promo", type: "boolean" },
    { csv: "CAMPAIGN_ID", db: "campaign_id", type: "string" },
    { csv: "CAMPAIGN_TYPE", db: "campaign_type", type: "string" },
    { csv: "CAMPAIGN_CREATED_DT", db: "campaign_created_dt", type: "date" },
    { csv: "CAMPAIGN_FINISHED_DT", db: "campaign_finished_dt", type: "date" },
    { csv: "ITEM_ID", db: "item_id", type: "integer" },
    { csv: "VERTICAL_ITEM", db: "vertical_item", type: "string" },
    { csv: "ITEM_NAME", db: "item_name", type: "string" },
    { csv: "DISCOUNT_SELLER_PERCENTAGE", db: "discount_seller_percentage", type: "number" },
    { csv: "DISCOUNT_TOTAL", db: "discount_total", type: "number" },
    { csv: "PEDIDOS_7D", db: "pedidos_7d", type: "number" },
    { csv: "MEDIA_TSI_DIARIO_7D", db: "media_tsi_diario_7d", type: "number" },
    { csv: "ESTOQUE_MEDIO_7D", db: "estoque_medio_7d", type: "number" },
    { csv: "ESTOQUE_MEDIO_FULL_7D", db: "estoque_medio_full_7d", type: "number" },
    { csv: "DATA_ATUALIZACAO", db: "data_atualizacao", type: "date" },
  ],
};