project_id = "uepfrcrlxaasvijxyqrg"

[functions.import-csv]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.import-live-listings]
verify_jwt = false

[functions.import-eligibility]
verify_jwt = false